version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    volumes:
      - ./backend/src:/app/src
    depends_on:
      - db

  admin-panel:
    build:
      context: ./apps/admin-panel
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  client-app:
    build:
      context: ./apps/client-app
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - backend

  mobile:
    build:
      context: ./mobile
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: